kind: Service
apiVersion: v1
metadata:
  name: basic-server-service
spec:
  selector:
    app: basicSpring
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-server
  labels:
    app: basicSpring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basicSpring
  template:
    metadata:
      labels:
        app: basicSpring
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080