---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-spring-server
  #namespace: java
  labels:
    app: springapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springapi
  template:
    metadata:
      labels:
        app: springapi
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: springapi
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: basic-spring-service
  #namespace: go
spec:
  selector:
    app: springapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: basic-spring-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
    - host: spring.rancher.jiankowalski.com
      http:
        paths:
          - path: /
            backend:
              serviceName: basic-spring-service
              servicePort: 5000