
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server
  #namespace: spring
  labels:
    app: springapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapi
  template:
    metadata:
      labels:
        app: springapi
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: springapi
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: spring-service
  #namespace: spring
spec:
  selector:
    app: springapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: spring-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
    - host: spring.rancher.jiankowalski.com
      http:
        paths:
          - path: /
            backend:
              serviceName: spring-service
              servicePort: 8080