spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  liquibase:
    change-log: "db/changelog/db.changelog-master.xml"
server:
  port: 9000
  servlet:
    context-path: "/api"

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html