openapi: 3.0.2
info:
  title: Basic spring
  version: 1.0.0
  description: Projeto que servira de base para futuros projetos
  contact:
    name: Basic API
    email: jian_kowalski@com.br
servers:
  - url: localhost:8080/v3/api-docs
paths:
  /courses:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseModel'
          description: courses
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
          description: unexpected error
      operationId: findcourses
      description: |
        Retorna a lista de todos os cursos
    post:
      requestBody:
        description: Criar course
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInput'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseModel'
          description: courses
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
          description: unexpected error
      operationId: addCourse
      description: Criação de curso
  /courses/{id}:
    get:
      parameters:
        - name: id
          description: Id do courso
          schema:
            format: int64
            type: integer
          in: path
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseModel'
          description: course
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
          description: unexpected error
      operationId: findCourseById
      description: |-
        Retorna o courso pelo ID
    delete:
      parameters:
        - name: id
          description: Deletar courso
          schema:
            format: int64
            type: integer
          in: path
          required: true
      responses:
        "204":
          description: Curso deletado
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
          description: unexpected error
      operationId: deleteCourse
      description: Deleta o corso pelo ID
    parameters:
      - name: id
        description: ID Courso
        schema:
          type: integer
        in: path
        required: true
components:
  schemas:
    CourseModel:
      allOf:
        - $ref: '#/components/schemas/CourseInput'
        - required:
            - id
          properties:
            _id:
              format: int64
              type: integer
    CourseInput:
      required:
        - name
        - category
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 255
        category:
          type: string
          enum:
            - front-end
            - back-end
    Object:
      properties:
        name:
          type: string
        userMessage:
          type: string
    Problem:
      properties:
        status:
          format: int32
          type: integer
        timestamp:
          type: string
          format: date-time
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        userMessage:
          type: string
        objects:
          type: array
          items:
            $ref: '#/components/schemas/Object'