version: "3.6"
services:
  mysql:
    image: mysql/mysql-server:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_USER: courses
      MYSQL_PASSWORD: courses
    ports:
      - 3306:3306

  basic-spring:
    image: jianrk/api-courses-server-test:0.0.13-9714ef3
    ports:
      - 9000:80
    depends_on:
      - mysql
